### ISSUE TITLE
[FEAT] Add the created_at timestamp to the cards

### ISSUE THREAD

**Issue by Parsifal-M** [Parsifal-M/backstage-open-feedback#34]
We store the created_at in the database for each feedback, we should display it in the card itself so we know when it was logged.

We could display it at the bottom of the card.

**Comment by chihab1991** [comment]
Hi after viewing the code i think we should modify `OpenFeedBackCard` components just want to know it what format created_at is stored

**Comment by Parsifal-M** [comment]
> Hi after viewing the code i think we should modify `OpenFeedBackCard` components. also if you can specify the format you want the date to be displayed.

Hey! 👋 

Thanks for taking interest in contributing!

So you can find the code here: https://github.com/Parsifal-M/backstage-open-feedback/blob/main/plugins/open-feedback-backend/migrations/20240503151050_openfeedback_table.js#L11 

And this uses Knex.js (Postgres) which can be found here: https://knexjs.org/guide/schema-builder.html#timestamp

An example might look like `2023-04-12 14:30:00+02` in the card it would be nice if we could display it somewhere at the bottom/top and maybe in a `dd-mm-yyyy` format but I am open to suggestions here as well :)

Hope this helps!

**Comment by chihab1991** [comment]
I think the Dates are stored in the db like in this format `2023-04-12 14:30:00+02`

**Comment by Parsifal-M** [comment]
> I think the Dates are stored in the db like in this format `2023-04-12 14:30:00+02`

Awesome, is this something you'd like to work on? 👏

**Comment by chihab1991** [comment]
sure.

**Comment by Parsifal-M** [comment]
Done in #37 🥳
