### ISSUE TITLE
[FEAT] Support more than 255 characters

### ISSUE THREAD

**Issue by oliverchristen** [Parsifal-M/backstage-open-feedback#55]
**Is your feature request related to a problem? Please describe.**
When a user writes a feedback which is longer than the `feedbackText` field (255 characters), they get an internal server error.
![image](https://github.com/user-attachments/assets/cb581294-3990-4755-9f3b-80c3ce0108c9)

**Describe the solution you'd like**
I would like to support way more than only 255 characters, rather don't limit at all. And if it's limited, the user shall not be able to put in more than the supported number of characters.

**Describe alternatives you've considered**
Show an error message instead of sending the request.

**Comment by Parsifal-M** [comment]
Makes sense, we can just remove the character limit entirely I think!
